name: passem
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  domain:
    path: domain
  data:
    path: data
  flutter_form_bloc:
    path: plugins/flutter_form_bloc
  paginate_firestore:
    path: plugins/paginate_firestore
  firebase_analytics: "^7.0.1"
#  google_fonts: ^1.1.2
  flutter_bloc: ^7.0.0-nullsafety.3
  # Customized snackBars.
  flushbar: ^1.10.4
  # Loading network images and caching them.
  cached_network_image: ^3.0.0-nullsafety
  dropdown_search: ^0.4.8
  intl: ^0.17.0-nullsafety.2
  get_it: ^6.0.0
  modal_bottom_sheet: ^2.0.0-nullsafety.1
# Used to handle permission requests on android and ios.
  permission_handler: ^6.0.1
  file_picker: ^3.0.0
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.1
  flutter_icons: ^1.1.0
  auto_route: ^0.6.9
  open_file: ^3.1.0
# makes the layout responsive for different screen sizes.
  responsive_framework: ^0.0.14
  url_launcher: ^6.0.2
  native_pdf_view: ^4.0.1
  http: ^0.13.0
  path_provider: ^2.0.1
  path: ^1.7.0
  share: ^2.0.1
  device_info: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.10
  build_runner: ^1.11.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_intl:
  main_locale: en_US
  enabled: true
