name: passem
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  domain:
    path: domain
  data:
    path: data

  firebase_analytics: "^7.0.1"

  google_fonts: ^1.1.2

  #flutter_form_bloc: ^0.19.0
  flutter_bloc: ^6.1.2

  # Customized snackBars.
  flushbar: ^1.10.4

  # Loading network images and caching them.
  cached_network_image: ^2.5.0

  dropdown_search: ^0.4.8

  intl: ^0.17.0-nullsafety.2

  get_it: ^5.0.6

# Used to handle permission requests on android and ios.
  permission_handler: ^5.1.0+2

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.1
  flutter_icons: ^1.1.0
  auto_route: ^0.6.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  bloc_test: ^7.0.0
  mockito: ^4.1.4
  auto_route_generator: ^0.6.10
  build_runner: ^1.11.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_intl:
  main_locale: en_US
  enabled: true
